### ISSUE TITLE
Cargo Test Threading Issue

### ISSUE THREAD

**Issue by TristanB22** [Lind-Project/safeposix-rust#66]
When we run the tests concurrently then cargo errors out. This still needs more information, though.

**Comment by rennergade** [comment]
Can you add the error messages?

**Comment by TristanB22** [comment]
``` Finished test [unoptimized + debuginfo] target(s) in 3.48s
     Running unittests (target/debug/deps/safeposix_rust-c417db7b1da2bdbb)

running 3 tests
["Cargo.toml", "target", "tests", "Cargo.lock", "docs", "README.md", ".gitignore", ".git", "src"]
["Cargo.toml", "target", "foobar", "tests", "Cargo.lock", "docs", "README.md", ".gitignore", ".git", "src"]
Ok(9)
Ok("\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}")
Ok(9)
Ok("fizzbuzz!")
Ok(())
Ok(())
test interface::file::tests::filewritetest ... ok
Error in syscall: bind - EINVAL: The socket is already bound to an address
Error in syscall: bind - EADDRINUSE: Another socket is already bound to this addr
Error in syscall: release - EINVAL: provided port is not being used
thread 'tests::fs_tests::fs_tests::test_fs' panicked at 'attempt to subtract with overflow', src/safeposix/syscalls/fs_calls.rs:1175:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tests::networking_tests::net_tests::net_tests' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/safeposix/syscalls/fs_calls.rs:1135:55
test tests::fs_tests::fs_tests::test_fs ... FAILED
test tests::networking_tests::net_tests::net_tests ... FAILED

failures:

failures:
    tests::fs_tests::fs_tests::test_fs
    tests::networking_tests::net_tests::net_tests

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.17s

error: test failed, to rerun pass '--bin safeposix-rust' ```

It seems like the locks are poisoned?

**Comment by rennergade** [comment]
This only happens when running tests concurrently? It's not clear from the error message that this is due to threading, so you should isolate this first.

**Comment by rennergade** [comment]
@TristanB22 was this ever resolved?

**Comment by TristanB22** [comment]
Not yet -- I haven't had time to look at this yet.
